{"name": "Проверить авторизацию с неверным паролем", "status": "broken", "statusDetails": {"message": "TypeError: InventoryPage.check_inventory_page_open() takes 1 positional argument but 2 were given", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"b34cdf431e335920e7dde20be40e3af3\")>\n\n    @allure.title('Проверить авторизацию с неверным паролем')\n    def test_invalid_auth(driver):\n        auth_page = LoginPage(driver)\n        with allure.step('Ввести корректный логин'):\n            auth_page.input_login('standard_user')\n        with allure.step('Ввести некорректный пароль'):\n            auth_page.input_password('123')\n        with allure.step('Нажать кнопку \"Login\"'):\n            auth_page.login_button_click()\n    \n        with allure.step('Проверить работоспособность аутентификации'):\n>           assert InventoryPage(driver).check_inventory_page_open(\n                    \"[Failed]: failed authentication, wrong login or password\"\n                    )\nE           TypeError: InventoryPage.check_inventory_page_open() takes 1 positional argument but 2 were given\n\ntest_run.py:51: TypeError"}, "steps": [{"name": "Ввести корректный логин", "status": "passed", "steps": [{"name": "Ввести логин", "status": "passed", "parameters": [{"name": "login", "value": "'standard_user'"}], "start": 1732962903727, "stop": 1732962903807}], "start": 1732962903727, "stop": 1732962903807}, {"name": "Ввести некорректный пароль", "status": "passed", "steps": [{"name": "Ввести пароль\"", "status": "passed", "parameters": [{"name": "password", "value": "'123'"}], "start": 1732962903807, "stop": 1732962903859}], "start": 1732962903807, "stop": 1732962903859}, {"name": "Нажать кнопку \"Login\"", "status": "passed", "steps": [{"name": "Нажать кнопку \"LOGIN\"", "status": "passed", "start": 1732962903859, "stop": 1732962903916}], "start": 1732962903859, "stop": 1732962903916}, {"name": "Проверить работоспособность аутентификации", "status": "broken", "statusDetails": {"message": "TypeError: InventoryPage.check_inventory_page_open() takes 1 positional argument but 2 were given\n", "trace": "  File \"D:\\Programming\\SimbirSoft\\first_ui_test\\test_run.py\", line 51, in test_invalid_auth\n    assert InventoryPage(driver).check_inventory_page_open(\n  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Проверить, что открыта страница \"https://www.saucedemo.com/inventory.html\"", "status": "broken", "statusDetails": {"message": "TypeError: InventoryPage.check_inventory_page_open() takes 1 positional argument but 2 were given\n", "trace": "  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n"}, "start": 1732962903916, "stop": 1732962903916}], "start": 1732962903916, "stop": 1732962903928}], "attachments": [{"name": "log", "source": "9e1ae227-9cec-4dc9-89b6-040ef40012c5-attachment.txt", "type": "text/plain"}], "start": 1732962903727, "stop": 1732962903928, "uuid": "35a04c11-6c08-459f-9f85-5e87b334f094", "historyId": "f6344309a7b9cafdf393e373ce72372e", "testCaseId": "f6344309a7b9cafdf393e373ce72372e", "fullName": "test_run#test_invalid_auth", "labels": [{"name": "suite", "value": "test_run"}, {"name": "host", "value": "DESKTOP-KL1CQLF"}, {"name": "thread", "value": "1364-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_run"}]}